/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thegameoflifejava;

import java.awt.Canvas;
import java.awt.Graphics;
import javax.swing.JFrame;
import javax.json.JSONParser;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
 

public class App extends Canvas {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Game of Life");
        Canvas canvas = new Main();
        canvas.setSize(400, 400);
        frame.add(canvas);
        frame.pack();
        frame.setVisible(true);

        JSONParser jsonParser = new JSONParser();
         
        try (FileReader reader = new FileReader("employees.json"))
        {
            //Read JSON file
            Object obj = jsonParser.parse(reader);
 
            JSONArray employeeList = (JSONArray) obj;
            System.out.println(employeeList);
        }
    }

    public void paint(Graphics g) {
        g.fillOval(100, 100, 200, 200);
    }
}
